# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konfirm < Formula
  desc "Confirm your kubectl"
  homepage "https://github.com/Jaehyeon1020/konfirm"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.0/konfirm_0.8.0_darwin_amd64.tar.gz"
      sha256 "975cd75d4b50c31ce0f77ae1093e6d6aa8736531803c464ae1126daa173a34e9"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.0/konfirm_0.8.0_darwin_arm64.tar.gz"
      sha256 "6375edb8892c0da56bad5d09c37dbdc840ddb9a520a0a4936e6bd0f92072211e"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.0/konfirm_0.8.0_linux_amd64.tar.gz"
      sha256 "94032bc404a0aaaea849dc6884a6296eb963349bc0cba0294afafe2f3e23d25f"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.0/konfirm_0.8.0_linux_arm64.tar.gz"
      sha256 "37240b9cb2fc612883076778ebcde4252b14a6ecdc79ed745b53ad2872c15c9f"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  def caveats
    <<~EOS
      \e[33;1mZsh completion requires compinit and loading konfirm's completion script.
      Copy and run this:\e[0m

      \e[33m{
        echo ''
        echo '# konfirm setup'
        echo 'autoload -Uz compinit && compinit'
        echo 'source <(konfirm completion zsh)'
      } >> ~/.zshrc

      source ~/.zshrc\e[0m
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/konfirm version")
  end
end
