# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konfirm < Formula
  desc "Confirm your kubectl"
  homepage "https://github.com/Jaehyeon1020/konfirm"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.3/konfirm_0.8.3_darwin_amd64.tar.gz"
      sha256 "093595d4ddba24dfed68e88f5c2fe77e06304848563e673f7e294736bfdbe6b6"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.3/konfirm_0.8.3_darwin_arm64.tar.gz"
      sha256 "56ec2dda1bf10ec823db44e89beac2276487383db884daf6b0682d00753e5d08"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.3/konfirm_0.8.3_linux_amd64.tar.gz"
      sha256 "feecb80430762245825ed7e770181cb1babd50a4cc556abb0bef9e635bab810c"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.8.3/konfirm_0.8.3_linux_arm64.tar.gz"
      sha256 "f1f6e27130abc86db2d4c2f4b8b0d7d6d988c324d244d933aaaade14ffd457b8"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  def caveats
    <<~EOS
      \e[33;1mZsh completion requires compinit and loading konfirm's completion script.
      Copy and run this:\e[0m

      \e[33m{
        echo ''
        echo '# konfirm setup'
        echo 'autoload -Uz compinit && compinit'
        echo 'source <(konfirm completion zsh)'
      } >> ~/.zshrc

      source ~/.zshrc\e[0m
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/konfirm version")
  end
end
