# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konfirm < Formula
  desc "Confirm your kubectl"
  homepage "https://github.com/Jaehyeon1020/konfirm"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.9.0/konfirm_0.9.0_darwin_amd64.tar.gz"
      sha256 "cdf4de4e5ec3947f0700f17bfedb97f10597bf6e568fabbbd96b014d716ce7c5"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.9.0/konfirm_0.9.0_darwin_arm64.tar.gz"
      sha256 "63aa832e816e605756a61435d7acd6c9053cc84c3fbe3e12ebe1d1019a6c71c3"

      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.9.0/konfirm_0.9.0_linux_amd64.tar.gz"
      sha256 "c1447b22579a098a5540805eec61cb16123742cbccba1ee193c84dda71ee1e6a"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jaehyeon1020/konfirm/releases/download/v0.9.0/konfirm_0.9.0_linux_arm64.tar.gz"
      sha256 "8c3c8c3b1803079d10d095dda8180cf82dbd4aa46d85d296eace5cd357b98ac6"
      define_method(:install) do
        bin.install "konfirm"

        zsh_output = Utils.safe_popen_read(bin/"konfirm", "completion", "zsh")
        (buildpath/"_konfirm").write zsh_output
        zsh_completion.install "_konfirm"
      end
    end
  end

  def caveats
    <<~EOS
      \e[33;1mZsh completion requires compinit and loading konfirm's completion script.
      Copy and run this:\e[0m

      \e[33m{
        echo ''
        echo '# konfirm setup'
        echo 'autoload -Uz compinit && compinit'
        echo 'source <(konfirm completion zsh)'
      } >> ~/.zshrc

      source ~/.zshrc\e[0m
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/konfirm version")
  end
end
